### ISSUE TITLE
By general Python convention, filenames should be lowercased.

### ISSUE THREAD

**Issue by jperras** [fictivekin/err-tell#1]
Unless this is a specific implementation detail that is required for Errbot plugins to function, of course.

**Comment by jnhmcknight** [comment]
...and I don't remember the crazy command to do it when you have a case-insensitive filesystem.

Pretty sure it's not an errbot requirement, but I'll double check. It just has to match the data in the `*.plug` file on the `module =` line.

**Comment by jnhmcknight** [comment]
Got it. And no, it was not and Errbot requirement. Closing.
